package com.app.ui.user.alumno.view;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.Table;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { … }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class AlumnoPerfilView extends HorizontalLayout {
	protected VerticalLayout verticalLayout;
	protected HorizontalLayout horizontalLayout;
	protected Image image;
	protected Table table;
	protected TabSheet itemsEvaluables;
	protected HorizontalLayout containerButtons;
	protected VerticalLayout verticalLayout2;

	public AlumnoPerfilView() {
		Design.read(this);
	}
}
